# ================================
#
# Legend:
#
# `M` in bindings means `Alt` key
# `-n` means no-leader
#
# ================================

unbind -a -T root           # unbind orphaned shortcuts

# reload config
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display " Config reloaded!"

# truecolor
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc:RGB"

set -g prefix M-a           # leader
set -g mouse on             # mouse interaction
set -s escape-time 0        # no wait after `Esc`

# Session
# =======
bind X confirm-before -p " Kill session #S? (y/n)" kill-session
bind < command-prompt -I "#S" -p " Rename session:" "rename-session '%%'"

# create
bind C command-prompt -p " Session name:" "new-session -s '%%'"

# switch
bind -n M-w choose-tree
bind -n M-s choose-session
bind -n M-n switch-client -n
bind -n M-p switch-client -p

# Window
# ======
bind x confirm-before -p " Kill window #I:#W? (y/n)" kill-window
bind , command-prompt -I "#W" -p " Rename window:" "rename-window '%%'"

set -g base-index 1         # indexing from 1
set -g renumber-windows on  # renumber on close

# create
bind c new-window

# switch
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Pane
# ====
bind -n M-x confirm-before -p " Kill pane #P? (y/n)" kill-pane
bind -n M-, command-prompt -I "#T" -p " Rename pane:" "select-pane -T '%%'"

set -g pane-base-index 1   # indexing from 1
bind -n M-z resize-pane -Z  # fullscreen

# create
bind -n M-\' split-window -h # vertical
bind -n M-v split-window -v # horizontal

# switch
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Popup
# =====
bind -n M-c display-popup -E -w 80% -h 90%

# Copy mode
# =========
set -g mode-keys vi         # vim keybinds in copy mode
set -g set-clipboard on     # use system clipboard

# vim like copy & search bindings
bind -T copy-mode-vi v send -X begin-selection       # line selection
bind -T copy-mode-vi C-v send -X rectangle-toggle    # block selection
# copy by `y`
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
# search down
bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
# search top
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"

# Statusbar
# =========
set -g status-interval 15 # sec
set -g status-style "bg=default,fg=default"

set -g status-left-length 15
set -g status-left-style "bg=default,fg=default"
set -g status-left "[#S] "

set -g status-right-style "bg=default,fg=default"
set -g status-right "#{?client_prefix,⌨ ,  } %H:%M"

set -g window-status-style "bg=default,fg=default"
set -g window-status-format " #I:#W "

#set -g window-status-current-style "bg=default,fg=default"
set -g window-status-last-style "bg=default,fg=default"

set -g message-style "bg=colour4,fg=black"

# Plugins
# =======
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @continuum-restore "on"
set -g @continuum-save-interval 15 # min
run "~/.config/tmux/plugins/tpm/tpm"

